site_name: PythonActions
site_description: Python actions examples
site_author: Allan Almazan

repo_url: https://github.com/aalmazan/python-actions
edit_uri: https://github.com/aalmazan/python-actions/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
